SOLAR_TERMS_EN = {
    0: "chunfen",
    1: "qingming",
    2: "guyu",
    3: "lixia",
    4: "xiaoman",
    5: "mangzhong",
    6: "xiazhi",
    7: "xiaoshu",
    8: "dashu",
    9: "liqiu",
    10: "chushu",
    11: "bailu",
    12: "qiufen",
    13: "hanlu",
    14: "shuangjiang",
    15: "lidong",
    16: "xiaoxue",
    17: "daxue",
    18: "dongzhi",
    19: "xiaohan",
    20: "dahan",
    21: "lichun",
    22: "yushui",
    23: "jingzhe"
}